FROM python:3.9-slim

WORKDIR /app

# Install system dependencies
RUN apt-get update && apt-get install -y \
    build-essential \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Install Python dependencies with specific versions to avoid compatibility issues
RUN pip install --no-cache-dir numpy==1.22.4
RUN pip install --no-cache-dir pandas==1.4.2
RUN pip install --no-cache-dir streamlit==1.22.0 requests==2.28.2

# Copy the Streamlit app files
COPY ./src/streamlit_app/*.py .

EXPOSE 8501

CMD ["streamlit", "run", "app.py", "--server.port=8501", "--server.address=0.0.0.0"]
